version: '3.1'

services:

  db:
    container_name: database_test
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks:
      - botnet

  helpbot:
    container_name: helpbot
    build:
      context: .
    command: python finds.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db

networks:
  botnet:
    driver: bridge